services:
  web:
    build: .
    image: frog
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - BLOG_NAME=Frog
      - BLOG_INTRO=Gua Gua Gua~
      - SECRET_KEY=<your_blog_secret_key>
    depends_on:
      - redis

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass <your_redis_password>
